name: CI

on:
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  backend:
    name: Backend - Lint and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Lint
        run: |
          poetry run ruff check app tests
          poetry run black --check app tests
      - name: Test
        run: poetry run pytest

  frontend:
    name: Frontend - Lint, Test, Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Format check
        run: npm run format:check
      - name: Unit tests
        run: npm test -- --run
      - name: Build
        run: npm run build
